import os
import pytest
from sqlalchemy import create_engine, inspect
from alembic.config import Config
from alembic import command
from app.db.models import Base

@pytest.fixture(scope="session")
def engine():
    # Use an in-memory SQLite database or file-based for testing schema
    db_path = "sqlite:///./test_schema.db"
    os.environ["DATABASE_URL"] = db_path
    
    if os.path.exists("./test_schema.db"):
        os.remove("./test_schema.db")
        
    engine = create_engine(db_path)
    
    # Run Alembic migrations to head
    alembic_cfg = Config("alembic.ini")
    alembic_cfg.set_main_option("sqlalchemy.url", db_path)
    command.upgrade(alembic_cfg, "head")
    
    yield engine
    
    engine.dispose()
    
    if os.path.exists("./test_schema.db"):
        os.remove("./test_schema.db")

def test_alembic_schema_matches_models(engine):
    """
    Verifies that the schema generated by running all Alembic migrations
    matches the models defined in db.models exactly (no missing tables).
    """
    inspector = inspect(engine)
    
    # Get all tables from the database (migrated by Alembic)
    db_tables = set(inspector.get_table_names())
    # Alembic creates an alembic_version table, ignore it
    db_tables.discard('alembic_version')
    
    # Get all tables from the SQLAlchemy models
    model_tables = set(Base.metadata.tables.keys())
    
    # Compare
    assert model_tables == db_tables, f"Mismatch! Models: {model_tables}, DB: {db_tables}"
    
    # Compare columns
    for table_name in model_tables:
        db_columns = {col['name'] for col in inspector.get_columns(table_name)}
        model_columns = {col.name for col in Base.metadata.tables[table_name].columns}
        assert model_columns == db_columns, f"Column mismatch in {table_name}! Models: {model_columns}, DB: {db_columns}"
