"""Add conversation state

Revision ID: 20b98c7f601b
Revises: ee2f7e23a0f6
Create Date: 2026-07-05 18:39:26.950223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b98c7f601b'
down_revision: Union[str, Sequence[str], None] = 'ee2f7e23a0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('active_topic', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('last_order_id', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('turn_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'turn_count')
    op.drop_column('conversations', 'last_order_id')
    op.drop_column('conversations', 'active_topic')
    # ### end Alembic commands ###
