"""Add pinned_message_id

Revision ID: 280e48edd1c4
Revises: f4aa25bd0490
Create Date: 2026-07-08 16:00:19.102402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280e48edd1c4'
down_revision: Union[str, Sequence[str], None] = 'f4aa25bd0490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    columns_conversations = [c['name'] for c in inspector.get_columns('conversations')]
    if 'pinned_message_id' not in columns_conversations:
        op.add_column('conversations', sa.Column('pinned_message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'pinned_message_id')
    # ### end Alembic commands ###
