"""add role to agent

Revision ID: 3aba8de29bec
Revises: 1b83667c89bb
Create Date: 2026-07-04 22:20:34.961289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aba8de29bec'
down_revision: Union[str, Sequence[str], None] = '1b83667c89bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('role', sa.String(), nullable=False, server_default='manager'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'role')
    # ### end Alembic commands ###
