"""Add TOTP fields to Agent

Revision ID: 3e5f2c6b5e18
Revises: 80346562e83c
Create Date: 2026-07-18 13:06:57.685089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5f2c6b5e18'
down_revision: Union[str, Sequence[str], None] = '80346562e83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # Removed unsupported sqlite command
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed unsupported sqlite command
    op.drop_column('agents', 'totp_enabled')
    op.drop_column('agents', 'totp_secret')
    # ### end Alembic commands ###
