"""Add merged_into_id

Revision ID: 4cb989273aa6
Revises: 8cef3150df87
Create Date: 2026-08-04 11:11:49.504902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb989273aa6'
down_revision: Union[str, Sequence[str], None] = '8cef3150df87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merged_into_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_conversations_merged_into_id', 'conversations', ['merged_into_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_merged_into_id', type_='foreignkey')
        batch_op.drop_column('merged_into_id')

    # ### end Alembic commands ###
