"""Add full_name to agents

Revision ID: 68e2eb81273a
Revises: b6847edf8403
Create Date: 2026-07-05 10:28:45.278573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e2eb81273a'
down_revision: Union[str, Sequence[str], None] = 'b6847edf8403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'full_name')
    # ### end Alembic commands ###
