"""Add author_username to messages

Revision ID: 80346562e83c
Revises: c030af5dab25
Create Date: 2026-07-16 22:28:24.577485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80346562e83c'
down_revision: Union[str, Sequence[str], None] = 'c030af5dab25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'author_username')
    # ### end Alembic commands ###
