"""Add SavedView table

Revision ID: 8cef3150df87
Revises: 4b74a2b223b0
Create Date: 2026-08-03 18:21:43.232855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cef3150df87'
down_revision: Union[str, Sequence[str], None] = '4b74a2b223b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_views',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filter_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_views_agent_username'), ['agent_username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_views_agent_username'))

    op.drop_table('saved_views')
    # ### end Alembic commands ###
