"""Add handled_by to conversations

Revision ID: 9c1f42aa2b29
Revises: 3aba8de29bec
Create Date: 2026-07-04 23:07:49.587664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1f42aa2b29'
down_revision: Union[str, Sequence[str], None] = '3aba8de29bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    columns_conversations = [c['name'] for c in inspector.get_columns('conversations')]
    if 'handled_by' not in columns_conversations:
        op.add_column('conversations', sa.Column('handled_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'handled_by')
    # ### end Alembic commands ###
