"""Add sentiment and language to conversations

Revision ID: b488f5b49b05
Revises: 280e48edd1c4
Create Date: 2026-07-12 10:19:33.403971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b488f5b49b05'
down_revision: Union[str, Sequence[str], None] = '280e48edd1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('conversations')]
    
    if 'sentiment' not in columns:
        columns_conversations = [c['name'] for c in inspector.get_columns('conversations')]
        if 'sentiment' not in columns_conversations:
            op.add_column('conversations', sa.Column('sentiment', sa.String(), nullable=True))
    if 'language' not in columns:
        columns_conversations = [c['name'] for c in inspector.get_columns('conversations')]
        if 'language' not in columns_conversations:
            op.add_column('conversations', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'short_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
