"""Add employee_id to agents

Revision ID: b6847edf8403
Revises: 9c1f42aa2b29
Create Date: 2026-07-04 23:16:02.957685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6847edf8403'
down_revision: Union[str, Sequence[str], None] = '9c1f42aa2b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    columns_agents = [c['name'] for c in inspector.get_columns('agents')]
    if 'employee_id' not in columns_agents:
        op.add_column('agents', sa.Column('employee_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_agents_employee_id'), 'agents', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_employee_id'), table_name='agents')
    op.drop_column('agents', 'employee_id')
    # ### end Alembic commands ###
