"""Add intent_category and language

Revision ID: c030af5dab25
Revises: b488f5b49b05
Create Date: 2026-07-12 13:27:45.867908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c030af5dab25'
down_revision: Union[str, Sequence[str], None] = 'b488f5b49b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('intent_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'intent_category')
    # ### end Alembic commands ###
