"""Add is_pinned to Message

Revision ID: f3b12c285d84
Revises: a1c9f3e7d2b4
Create Date: 2026-07-29 19:34:04.268205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b12c285d84'
down_revision: Union[str, Sequence[str], None] = 'a1c9f3e7d2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required here: this table already has rows in
    # production, and Postgres enforces NOT NULL immediately on
    # ALTER TABLE ADD COLUMN — without a default to backfill existing
    # rows, it fails with NotNullViolation. SQLite's batch-mode ALTER
    # TABLE (table recreate) doesn't hit this the same way, which is why
    # this passed in local/SQLite testing but failed on Postgres.
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
